// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBanner: typeof import('./components/AppBanner/index.vue')['default']
    Components: typeof import('./components/index.vue')['default']
    MButton: typeof import('./components/MButton.vue')['default']
    MInput: typeof import('./components/MInput.vue')['default']
    MModal: typeof import('./components/MModal.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestCarousel: typeof import('./components/TestCarousel.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
