// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBanner: typeof import('./components/AppBanner/index.vue')['default']
    Camera: typeof import('./components/Camera.vue')['default']
    CaptureImageButton: typeof import('./components/CaptureImageButton.vue')['default']
    Components: typeof import('./components/index.vue')['default']
    EditTags: typeof import('./components/EditTags.vue')['default']
    ImageResizer: typeof import('./components/ImageResizer.vue')['default']
    MButton: typeof import('./components/shared/MButton.vue')['default']
    MCarousel: typeof import('./components/shared/MCarousel.vue')['default']
    MealData: typeof import('./components/MealData.vue')['default']
    MHistory: typeof import('./components/MHistory.vue')['default']
    MInput: typeof import('./components/shared/MInput.vue')['default']
    MModal: typeof import('./components/shared/MModal.vue')['default']
    MTag: typeof import('./components/shared/MTag.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestCarousel: typeof import('./components/TestCarousel.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
